name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: "test"
          

      - name: add conda channels
        run: |
          conda config --append channels nsls2forge
          conda config --append channels conda-forge

      - name: install requirements
        run: >-
          conda create -n test --file requirements/build.txt --file requirements/run.txt --file
          requirements/test.txt --file requirements/docs.txt

      - name: install the package
        run: python -m pip install .

      - name: check code style
        run: flake8

      - name: build documents
        run: make -C docs html

      - name: deploy to github pages if released
        uses: JamesIves/github-pages-deploy-action@3.5.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
